---
platform: linux

params:
  GOOS:
  GOARCH:
  OUTPUT_FILE:

inputs:
- name: concourse-up
- name: version
- name: compilation-vars

outputs:
- name: build

run:
  path: concourse-up/ci/tasks/build.sh
