---
platform: linux

params:
  GOOS: darwin
  GOARCH:
  OUTPUT_FILE:

inputs:
- name: concourse-up
- name: version
- name: compilation-vars

outputs:
- name: build-darwin

run:
  path: concourse-up/ci/tasks/build.sh
