---
platform: linux

inputs:
- name: concourse-up
- name: concourse-github-release
- name: concourse-stemcell
- name: director-stemcell
- name: director-bosh-release
- name: director-bosh-cpi-release

outputs:
- name: compilation-vars

run:
  path: concourse-up/ci/tasks/compile-bosh-releases.sh

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:
  PUBLIC_ARTIFACTS_BUCKET:
  BOSH_USERNAME:
  BOSH_PASSWORD:
  BOSH_CA_CERT:
  BOSH_TARGET: