---
platform: linux

inputs:
- name: concourse-up

run:
  path: concourse-up/ci/tasks/system-test.sh

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION: eu-west-1
  DOMAIN:
  TLS_CERT:
  TLS_KEY: