---
platform: linux

inputs:
- name: concourse-up
  path: go/src/bitbucket.org/engineerbetter/concourse-up

run:
  path: go/src/bitbucket.org/engineerbetter/concourse-up/ci/tasks/system-test.sh

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
