---
resources:
- name: concourse-up-image-source
  type: git
  source:
    uri: git@bitbucket.org:engineerbetter/concourse-up.git
    branch: master
    private_key: {{private_key}}
    paths: [ci/docker/*]

- name: concourse-up-image
  type: docker-image
  source:
    repository: engineerbetter/cup-image
    username: {{docker_user}}
    password: {{docker_password}}

jobs:
- name: build-cup-image
  public: false
  plan:
  - get: concourse-up-image-source
    trigger: true
  - put: concourse-up-image
    params:
      build: concourse-up-image-source/ci/docker
