---
resources:
- name: image-source
  type: git
  source:
    uri: git@bitbucket.org:engineerbetter/concourse-up.git
    branch: master
    paths: [ci/docker/*]
    private_key: {{private_key}}

- name: concourse-up
  type: git
  source:
    uri: git@bitbucket.org:engineerbetter/concourse-up.git
    branch: master
    ignore_paths: [ci/docker/*, ci/pipeline.yml]
    private_key: {{private_key}}

- name: image
  type: docker-image
  source:
    repository: engineerbetter/cup-image
    username: {{docker_user}}
    password: {{docker_password}}

jobs:
- name: build-image
  public: false
  plan:
  - get: image-source
    trigger: true
  - put: image
    params:
      build: image-source/ci/docker

- name: test
  plan:
  - get: image
    trigger: true
    passed: [build-image]
  - get: concourse-up
    trigger: true
  - aggregate:
    - task: lint
      image: image
      file: concourse-up/ci/tasks/lint.yml
    - task: unit-test
      image: image
      file: concourse-up/ci/tasks/unit-test.yml
      params:
        AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
  - task: system-test
    image: image
    file: concourse-up/ci/tasks/system-test.yml
    params:
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
