---
resources:
- name: image-source
  type: git
  source:
    uri: https://github.com/EngineerBetter/concourse-up.git
    branch: master
    paths: [ci/docker/*]

- name: concourse-up
  type: git
  source:
    uri: https://github.com/EngineerBetter/concourse-up.git
    branch: master
    ignore_paths: [ci/docker/*, ci/pipeline.yml, README.md]

- name: image
  type: docker-image
  source:
    repository: engineerbetter/cup-image
    username: {{docker_user}}
    password: {{docker_password}}

- name: version
  type: semver
  source:
    initial_version: 0.0.0
    driver: s3
    bucket: concourse-up-ci-artifacts
    key: version
    access_key_id: {{aws_access_key_id}}
    secret_access_key: {{aws_secret_access_key}}
    region_name: eu-west-1

- name: release
  type: github-release
  source:
    user: engineerbetter
    repository: concourse-up
    access_token: {{github_access_token}}
    pre_release: true

jobs:
- name: build-image
  public: false
  plan:
  - get: image-source
    trigger: true
  - put: image
    params:
      build: image-source/ci/docker

- name: test
  plan:
  - get: image
    trigger: true
    passed: [build-image]
  - get: concourse-up
    trigger: true
  - aggregate:
    - task: lint
      image: image
      file: concourse-up/ci/tasks/lint.yml
    - task: unit-test
      image: image
      file: concourse-up/ci/tasks/unit-test.yml
      params:
        AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
  - task: system-test
    image: image
    file: concourse-up/ci/tasks/system-test.yml
    params:
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}

- name: release-patch
  serial: true
  plan:
  - get: version
    params:
      bump: patch
  - get: image
    passed:
    - test
  - get: concourse-up
    passed:
    - test
  - task: build
    image: image
    file: concourse-up/ci/tasks/build.yml
  - put: version
    resource: version
    params:
      file: version/version
  - put: release
    params:
      name: concourse-up/ci/release/name
      body: concourse-up/ci/release/body
      tag: version/version
      globs:
      - build/*

- name: release-minor
  serial: true
  plan:
  - get: version
    params:
      bump: minor
  - get: image
    passed:
    - test
  - get: concourse-up
    passed:
    - test
  - task: build
    image: image
    file: concourse-up/ci/tasks/build.yml
  - put: version
    resource: version
    params:
      file: version/version
  - put: release
    params:
      name: concourse-up/ci/release/name
      body: concourse-up/ci/release/body
      tag: version/version
      globs:
      - build/*

- name: release-major
  serial: true
  plan:
  - get: version
    params:
      bump: major
  - get: image
    passed:
    - test
  - get: concourse-up
    passed:
    - test
  - task: build
    image: image
    file: concourse-up/ci/tasks/build.yml
  - put: version
    resource: version
    params:
      file: version/version
  - put: release
    params:
      name: concourse-up/ci/release/name
      body: concourse-up/ci/release/body
      tag: version/version
      globs:
      - build/*
